### ISSUE TITLE
请问下你这个语音缺失估计的算法用的是那个算法，我这边看不太懂

### ISSUE THREAD

**Issue by WangQin-wq** [xiaochunxin/OMLSA-MCRA#1]

**Comment by WangQin-wq** [comment]
请问下你这个语音缺失估计的算法用的是那个算法，我这边看不太懂

**Comment by xiaochunxin** [comment]
还是按照论文原文做的，只是做了工程化，比较难看懂了。

**Comment by WangQin-wq** [comment]
看了论文大概理解了，首先我这边把16k采样率32位的含噪音频带入后降噪缺失很彻底，但同时也产生了比较严重的语音失真现象，但我看你demo中的结果语音几乎没有失真。其次，您这边的这个定点化和查表法是怎么操作的呢，能不能大概是解释下，我看你贴的链接，有的已经失效了。能否分享下！十分感谢
